In [1]:
import torch

c:\Users\uicha\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [64]:
model = torch.hub.load('ultralytics/yolov5','custom', 'yolov5s.pt')

Using cache found in C:\Users\uicha/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2022-11-27 Python-3.10.8 torch-1.13.0+cu117 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12288MiB)

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 


'cp949' codec can't decode byte 0xf0 in position 9: illegal multibyte sequence


In [65]:
import numpy as np
a = torch.zeros([1,3,640,640])
result = model(a).cpu().numpy()
result = result.reshape(result.shape[1:])
print(result.shape)

(25200, 85)


In [128]:
import cv2
image = cv2.imread("sample.png")
result = model(image).pandas().xyxy[0].to_numpy()
print(result)

result = model(image).xyxyn[0].cpu().numpy()[:, :-1]
result[:,:2] *= np.array([image.shape[1],image.shape[0]])
result[:,2:4] *= np.array([image.shape[1],image.shape[0]])
print(result)

[[84.40532684326172 99.15868377685547 179.13682556152344 147.6234130859375 0.9108076095581055 2 'car']
 [189.46414184570312 85.6251449584961 279.63641357421875 152.4964599609375 0.8077476024627686 2 'car']
 [338.9547424316406 74.58716583251953 402.8216552734375 147.392333984375 0.6368030309677124 2 'car']
 [342.93255615234375 9.565675735473633 434.9966125488281 258.9519958496094 0.4743460714817047 2 'car']]
[[     84.405      99.159      179.14      147.62     0.91081]
 [     189.46      85.625      279.64       152.5     0.80775]
 [     338.95      74.587      402.82      147.39      0.6368]
 [     342.93      9.5657         435      258.95     0.47435]]


In [62]:
help(model(image))

Help on Detections in module models.common object:

class Detections(builtins.object)
 |  Detections(ims, pred, files, times=(0, 0, 0), names=None, shape=None)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, ims, pred, files, times=(0, 0, 0), names=None, shape=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __len__(self)
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  __str__(self)
 |      Return str(self).
 |  
 |  crop(self, save=True, save_dir='runs/detect/exp', exist_ok=False)
 |  
 |  pandas(self)
 |  
 |  print(self)
 |  
 |  render(self, labels=True)
 |  
 |  save(self, labels=True, save_dir='runs/detect/exp', exist_ok=False)
 |  
 |  show(self, labels=True)
 |  
 |  tolist(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the